### ISSUE TITLE
cannot start with npx. Error about ejs.

### ISSUE THREAD

**Issue by rafipiccolo** [kefranabg/readme-md-generator#188]
**Describe the bug**
cannot start with npx. Error about ejs.

**To Reproduce**
```
# uname -a
Linux ideaz.world 4.9.58-xxxx-std-ipv6-64 #1 SMP Mon Oct 23 11:35:59 CEST 2017 x86_64 x86_64 x86_64 GNU/Linux
# node --version
v10.14.0
# npx readme-md-generator
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module '/root/.npm/_npx/11971/lib/node_modules/readme-md-generator/node_modules/ejs/postinstall.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ejs@2.7.4 postinstall: `node ./postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ejs@2.7.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-11-26T21_28_37_311Z-debug.log
Install for readme-md-generator@latest failed with code 1
```

**Expected behavior**
Should start program and create a readme

**Comment by kefranabg** [comment]
@rafipiccolo 

Please update you npm version and retry
