### ISSUE TITLE
Doesn't seem to work on macOs

### ISSUE THREAD

**Issue by wrecklass** [kefranabg/readme-md-generator#34]
Tried out your project on my MacBook Pro (Mojave macOs 10.14.5). After successfully installing using your notes, I attempted to run and get the following error:

```
usr/local/lib/node_modules/readme-md-generator/src/cli.js:14
const askQuestions = async projectInfos => {
                           ^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/readme-md-generator/src/index.js:5:25)
    at Module._compile (module.js:556:32)
```
Which is interesting as I can clearly see the require statement
```javascript
const projectInfos = require('./project-infos')
```
And project-infos.js appears to be fine.
Not knowledgable enough in node to debug it further myself.

**Comment by kefranabg** [comment]
Hi @wrecklass,
Do you have a node version under v8 ?

I will add prerequisites in README 😉

**Comment by kefranabg** [comment]
I added prerequisites badges to the README. Please get a recent version of node to use `readme-md-generator` 😉
